Esercitazione_task_gestione_impiegati/acc_task_gestione_impiegati/acc_task_gestione_impiegati/Models/Impiegato.cs
using System;
using System.Collections.Generic;

namespace acc_task_gestione_impiegati.Models;

public partial class Impiegato
{
    public int ImpiegatoId { get; set; }

    public string Matricola { get; set; } = null!;

    public string Nome { get; set; } = null!;

    public string Cognome { get; set; } = null!;

    public DateOnly DataNascita { get; set; }

    public string Ruolo { get; set; } = null!;

    public string Reparto { get; set; } = null!;

    public string IndirizzoResidenza { get; set; } = null!;

    public string CittaResidenza { get; set; } = null!;

    public string ProvinciaResidenza { get; set; } = null!;
}

Esercitazione_task_gestione_impiegati/acc_task_gestione_impiegati/acc_task_gestione_impiegati/Controllers/ImpiegatoController.cs
using acc_task_gestione_impiegati.Models;
using acc_task_gestione_impiegati.Services;
using Microsoft.AspNetCore.Mvc;

namespace acc_task_gestione_impiegati.Controllers
{
    public class ImpiegatoController : Controller
    {
        private readonly ImpiegatoService _service;

        public ImpiegatoController(ImpiegatoService service)
        {
            _service = service;
        }
        public IActionResult Inserimento()
        {
            return View();
        }
        [HttpPost]
        public RedirectResult Salvataggio(Impiegato objImpiegato)
        {
            if (_service.InserisciImpiegato(objImpiegato))
                return Redirect("/Impiegato/Lista");
            else
                return Redirect("/Impiegato/Errore");
        }

        public IActionResult Lista()
        {
            List<Impiegato> elenco = _service.ElencoImpiegati();

            return View(elenco);
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Esercitazione_task_gestione_impiegati/acc_task_gestione_impiegati/acc_task_gestione_impiegati/Views/Impiegato/Inserimento.cshtml
@model acc_task_gestione_impiegati.Models.Impiegato

<h1>Inserisci Impiegato</h1>

<form method="post" asp-controller="Impiegato" asp-action="Salvataggio">
    <div class="form-group">
        <label for="Matricola">Matricola</label>
        <input type="text" class="form-control" asp-for=Matricola />
    </div>
    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" class="form-control" asp-for=Nome />
    </div>
    <div class="form-group">
        <label for="Cognome">Cognome</label>
        <input type="text" class="form-control" asp-for=Cognome>
    </div>
    <div class="form-group">
        <label for="DataNascita">Data di nascita</label>
        <input type="date" min="0" class="form-control" asp-for=DataNascita />
    </div>
    <div class="form-group">
        <label for="Ruolo">Ruolo</label>
        <input type="text" class="form-control" asp-for=Ruolo />
    </div>
    <div class="form-group">
        <label for="Reparto">Reparto</label>
        <input type="text" min="0" class="form-control" asp-for=Reparto />
    </div>
    <div class="form-group">
        <label for="IndirizzoResidenza">Indirizzo di residenza</label>
        <input type="text" min="0" class="form-control" asp-for=IndirizzoResidenza />
    </div>
    <div class="form-group">
        <label for="ProvinciaResidenza">Provincia di residenza</label>
        <input type="text" min="0" class="form-control" asp-for=ProvinciaResidenza />
    </div>
    <div class="form-group">
        <label for="CittaResidenza">Città di residenza</label>
        <input type="text" min="0" class="form-control" asp-for=CittaResidenza />
    </div>   

    <button class="btn btn-primary btn-block" type="submit">Salva</button>
</form>

Esercitazione_task_gestione_impiegati/acc_task_gestione_impiegati/acc_task_gestione_impiegati/Views/Impiegato/Lista.cshtml
@model List<acc_task_gestione_impiegati.Models.Impiegato>

<h1>Lista degli impiegati</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Matricola</th>
            <th>Nome</th>
            <th>Cognome</th>
            <th>Data di nascita</th>
            <th>Ruolo</th>
            <th>Reparto</th>
            <th>Indirizzo di residenza</th>
            <th>Provincia di residenza</th>
            <th>Città di residenza</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Impiegato imp in Model)
        {
            <tr>
                <td>@imp.Matricola</td>
                <td>@imp.Nome</td>
                <td>@imp.Cognome</td>
                <td>@imp.DataNascita</td>
                <td>@imp.Ruolo</td>
                <td>@imp.Reparto</td>
                <td>@imp.IndirizzoResidenza</td>
                <td>@imp.ProvinciaResidenza</td>
                <td>@imp.CittaResidenza</td>
                <td>
                    <button class="btn btn-danger" type="button" onclick="elimina('@imp.Matricola')">Elimina</button>
                    <a class="btn btn-warning" href="/Impiegato/Modifica/@imp.Matricola">Modifica</a>
                </td>
            </tr>
        }
    </tbody>
</table>